Repository lblod/ember-rdfa-editor-besluit-plugin, pull requests merged in 2022-02, with the labels that each got.

#3 Use editor debug component instead of duplicated code (see GN-3152)
  package-lock.json
  package.json
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
Labels: enhancement

#4 Delete and move articles
  addon/besluit-plugin.js
  addon/commands/insert-article-command.js
  addon/commands/move-article-command.js
  addon/components/besluit-plugin-card.hbs
  addon/components/besluit-plugin-card.js
  package-lock.json
  package.json
Labels: enhancement

#5 Made new icons for the new actions
  addon/components/besluit-plugin-card.hbs
Labels: enhancement

#7 Ember upgrade v3.28
  .eslintignore
  .eslintrc.js
  .npmignore
  .template-lintrc.js
  .travis.yml
  CONTRIBUTING.md
  README.md
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
  tests/dummy/app/components/rdfa-editor-with-debug.js
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/application.hbs
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  tests/index.html
Labels: enhancement

#6 Explicit import of the debug component
  tests/dummy/app/components/rdfa-editor-with-debug.js
  tests/dummy/app/templates/application.hbs
Labels: bug

#8 chore/bump editor 0.50.0
  addon/components/besluit-plugin-card.js
  package-lock.json
  package.json
  tests/dummy/app/styles/app.scss
Labels: internal

#9 Make sure the selection after inserting title is inside the title
  addon/commands/insert-title-command.js
  addon/components/besluit-plugin-card.js
  addon/utils/get-title-for-decision.js
Labels: enhancement
